### PR TITLE
Generator framework

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/819. [See changes here.](https://github.com/csierra/liferay-portal/compare/22a5f589c976~8...22a5f589c976) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
