### PR TITLE
LPS-76926 Ability to revert micro changes in SchemaVersion

### PR DESCRIPTION
**Pull request by achaparro**
Hi @csierra,

This is the framework to implement this feature, after this we should apply it for all the modules or on demand. It seems that there is no way to implement a range because SimpleFilter in org.apache.felix.framework.capabilityset does not support neither range filter or < operator.

We talk this Monday.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/106. [See changes here.](https://github.com/csierra/liferay-portal/compare/e655f07~4...e655f07) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
please see https://github.com/achaparro/liferay-portal/pull/106

**Pull request closed without merging**
