### PR TITLE
LPS-111617 Store each corsSupport already configured

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35 @dantewang @slnn 

hey folks, as discussed with @shuyangzhou could you please run a regression test on this pull? It adds a new filter globally which will be disabled mostly all the time unless a CORS header comes in the request, so we don't expect the new logic to be hit, except to test if the header is present in the request. 
There are integration tests that would hit the new logic in case you would have a look at it in `portal-remote-cors-test` 

Thanks a ton. 

Bests.
Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:stable

**Comment by csierra** [comment]
c:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
/cc @martamedio 

added the bugfix here

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:close

**Pull request closed without merging**
