### PR TITLE
LPS-112805 Disable BASIC auth at company level

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@csierra I pushed another commit for the second acceptance criteria. However I cannot seem to get buildLang to regenerate the language resources. Can you try?

**Comment by csierra** [comment]
I will try

**Comment by csierra** [comment]
it works for me... but I would hold this one back a little while we finish merging the rest of MFA

**Comment by csierra** [comment]
Please see https://github.com/stian-sigvartsen/liferay-portal/pull/249

**Pull request closed without merging**
