### PR TITLE
LPS-105060 New test to check case without any scope

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81483. [See changes here.](https://github.com/csierra/liferay-portal/compare/05811c936e78~1...05811c936e78) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/martamedio/liferay-portal/pull/117. [See changes here.](https://github.com/csierra/liferay-portal/compare/0b2ae34d5682~6...0b2ae34d5682) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
