### PR TITLE
Generator framework

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @csierra ,
I dropped one of your auto SF commit as it was SFing gradle file, also corrected commit diff for 9b06e7a3698bcbd4d4a9223af136fdc1dc341917

I have 3 bigger concerns about introducing **saltGenerator**:
1. How does user get an instance of the **saltGenerator**, from **HashGeneratorFactory**? If so, then it seems like user has to call **hashGeneratorFactory** twice, one to get a **hashGenerator**, then to get a **saltGenerator**.
2. Even if the user has a instance of **saltGenerator**, how can the user invoke **generateSalt(int size)** 
3. How can the user know if the provider supports size in order to supply a size parameter?

Can we have a discussion before standup?

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
cc topolik

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arthurchan35** [comment]
Hi @csierra ,

As mentioned, resend you a new PR.

Added missing code back to the commit.
And organized directory little bit.

Thanks!

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81650. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
