### PR TITLE
[TS] LPS-115694

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/csierra/liferay-portal/pull/800 with a major rework of the solution as well as tests.  Please let me know if you have any questions, thanks!

CC @achaparro

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
You can reference the test results on the new pull.

**Comment by moltam89** [comment]
Hi guys,

I was asked to check this PR from Staging point of view.

The changes look good to me for Local Staging.
In case of Remote Staging however, NullPointer is thrown, because group.getStagingGroup() returns null.

Best,
Tamás

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/314

**Pull request closed without merging**
