### PR TITLE
LPS-71728 add support for new -aggregateresourcebundles bnd instruction to ResourceBundleLoaderAnalyzerPlugin

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
This `-aggregateresourcebundles` only handles that I think is the most common case, e.g. I want to load my content.Language as well as an aggregation of all other resource bundle content.Languages that I list on that instruction, preferring my own content.Language.  This instruction will encode the Provide/Require Caps in an identical fashion to how you have designed them, this just encapsulates all of that complex Provide/Require syntax into a simple bnd instruction. cc @jhinkey

**Comment by csierra** [comment]
hey @gamerson 
I have been out until today... will have a look soon!

**Comment by csierra** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by gamerson** [comment]
thanks @csierra  for taking a look!  Let me know if it isn't clear what I'm trying to do.

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/130. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/131. [See changes here.](https://github.com/csierra/liferay-portal/compare/ae4c260~1...ae4c260) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
