### PR TITLE
Lps 107195 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
@csierra 
I fixed the double instantiation and squashed the fix into your commit, also reorganized the commits a little bit.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by slnn** [comment]
Will run performance tests with this pull and update test results when I got them.
cc @shuyangzhou

**Comment by slnn** [comment]
Hi all,

Here are test resuts:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 44632 | 265 | 78.5 | -
PR | - | 44255 | 262 | 78.5 | -0.8446854275

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 56206 | 503 | 151 | -
PR | - | 56274 | 559 | 166 | 0.1209835249

MessageBoard:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 17794 | 27.7 | 76.9 | -
PR | - | 17728 | 32.1 | 80.7 | -0.3709115432

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 14712 | 357 | 371 | -
PR | - | 14523 | 601 | 491 | -1.284665579

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 25512 | 210 | 305 | -
PR | - | 26302 | 184 | 284 | 3.096582001

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 15177 | 243 | 461 | -
PR | - | 15592 | 239 | 457 | 2.734400738

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 15177 | 243 | 461 | -
PR | - | 15592 | 239 | 457 | 2.734400738

cc @shuyangzhou @arthurchan35  @csierra 

Regards
Lily

**Comment by arthurchan35** [comment]
Forwarded to: https://github.com/shuyangzhou/liferay-portal/pull/8865

**Pull request closed without merging**
