### PR TITLE
LPS-71580 Fix information leak in WebServerServlet

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:reopen

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48107. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
