### PR TITLE
LPS-105162 Sorted service.xml, upgrade, minor SF, missing lang keys, new tests

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Carlos. Following on from the test failure in csierra/liferay-portal/pull/606 I have fixed the existing test and added tests for the new behavior.

From the previous pull request... The main changes are the sorting for the SB service parameters and service.xml and upgrade process, but also found a few minor issues.

497d983 onwards is new.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83845. [See changes here.](https://github.com/csierra/liferay-portal/compare/4db4f620079c~2...4db4f620079c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83846. [See changes here.](https://github.com/csierra/liferay-portal/compare/cc35e0e80812~2...cc35e0e80812) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83847. [See changes here.](https://github.com/csierra/liferay-portal/compare/f84b333cc4da~2...f84b333cc4da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
