### PR TITLE
LPS-103385 Allow to remove property of legacy algorithm once all passwords were updated to current algorithm

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79878. [See changes here.](https://github.com/csierra/liferay-portal/compare/471d844cb57f~1...471d844cb57f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
