### PR TITLE
Lps 101568 bug

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2650. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
