### PR TITLE
Persistence for Config Admin Review

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Si te parece bien, podemos ir mergeando esto, y tratamos la configuración la semana que viene. Si te parece bien, puedes enviarla a master!

Muchas gracias!!

**Comment by csierra** [comment]
:+1:

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30281. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30289. [See changes here.](https://github.com/csierra/liferay-portal/compare/0f95bb4~1...0f95bb4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30306. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
