### PR TITLE
Lps 63730

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @brianchandotcom

### CODE REVIEW

**Comment by csierra** [comment]
hey @shuyangzhou,

simply removing the lock won't work, would it? we could end up having a `ready` state set to `true` while deregistering the `serviceRegistrar` or the other way around, having the portlet set to `ready=false` while keeping the service registered. I think we need to keep all the effects in sync.

**Comment by shuyangzhou** [comment]
Yes, your concern is correct, but to me, it is an issue inside ServiceRegistrar, not PortletImpl.

Force pushed new commits.

Let's see it this way.

PortletImpl is a registry of ServiceRegistrar, all it needs to do is to make sure concurrent check-in/check-out ServiceRegistrar is thread safe.

ServiceRegistrar should manage its own thread safety, not by PortletImpl.

As we separate the concerns, each one only needs to take care its own responsibilities.

Let me know if you have any other concerns about this new appended solution.

**Comment by csierra** [comment]
hey @shuyangzhou, 

I still have the same concern as before. Either I am missing something or with this we still wouldn't be synching `_readyMap` state with `_serviceRegistrars` state. So we could end up having a key in `_readyMap` to false while having a `ServiceRegistrar` in `_serviceRegistrars` for the same key and the `Portlet` instance registered, which would be incorrect. Or the other way around, having `_readyState` set to `true` while removing the `Portlet` instance from the framework and the `ServiceRegistrar` from `_serviceRegistrars`.

I believe we need to make the modifications to both `_readyMap` and `_serviceRegistrars` _atomically_ when they affect the same `rootPortletId`. This is what I tried to achieve with my fix. 

I will look to your modifications to `ServiceRegistrar` more carefully as they may be needed too.

**Comment by shuyangzhou** [comment]
Ok @csierra, I misread your intent on the original fix.

I thought you were only trying to fix the deadlock, now I realize you also wanted to keep those 2 maps in sync.

Syncing 2 maps is very very complex, but luckily our case is special, those 2 maps have the exact same keys.

Therefore, we don't really need 2 maps, just 1 map with a composite value type.

The downside of it is, the composite value type must be mutable. One (the ready boolean flag) can simplify be volatile, while the other one (the ServiceRegistrar) must be synced on modification as it is a multi-steps changes. But at least we only need to sync on the composite value that we are current modifying, the contention is low.

Force pushed again, let me know if anything else causes your concern.

Thanks

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @shuyangzhou,

it seems that this pull also suffers from the same problem as before, but now between `setReady` and `unsetReady`. If two threads compete there we could end up having a service in the registry while having no entry in `_readynessMap`.

What would you say if we abstracted out the _complexity_ of the current code to a module so we can reuse the logic? It would look great on Java 8 too... please have a look at https://github.com/shuyangzhou/liferay-portal/pull/2845

Bests.

**Comment by shuyangzhou** [comment]
@csierra That race condition can be fixed by the double check, force pushed. See the last commit.

**Comment by csierra** [comment]
hey...

this is doing basically the same thing as there is now, but treating it as a special case instead of a general case because we are using a composite key...

I would personally leave it as is now and abstract it out when we can use Java 8 in a couple of weeks.

**Comment by shuyangzhou** [comment]
Yes, that's basically what it is :) Except it only use one map, lesser overhead. 
But all the complexity will go away anyway after moving to jdk8. Just hold on for a couple more weeks.

Do you mind forward it to @brianchandotcom ?

Thanks!

**Comment by shuyangzhou** [comment]
Seems you are off for today, sent to @brianchandotcom at https://github.com/brianchandotcom/liferay-portal/pull/38873

**Comment by csierra** [comment]
I was only on the train... but help yourself...

I can't see the overhead you see but if this is so important for you... go ahead. I am out of arguments here. 

Cheers.

**Pull request closed without merging**
