### PR TITLE
[TS] LPS-98254 X-Forwarded-* headers are not being honored when main.servlet.https.required is set to true

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-98254

Hi Carlos,

@lipusz recently forwarded this pr to you, but we ran into some SF issues, which we decided to resolve, via source-formatter-supressions.xml.
- Reference: https://github.com/csierra/liferay-portal/pull/536

Below is the description from the previous pr:

> 
> The goal of this pr is to make sure **X-Forwarded-\* headers** are being accounted for.
> 
> **Additional Notes**
> 
> - For the steps to reproduce, applying the fix to BaseAuthFilter already resolves the issue.
>   - But, I noticed that AuthVerifierFilter had basically the same logic, so I made the changes there as well.
>   - I wasn't sure if we should consolidate the logic, since they are technically two different filters.
>   - And so, the approach I took was to just make changes to both filters and to create test classes for each filter.
> - I also noticed that the proxy path wasn't being accounted for, so I added to that as well.
> - Also, feel free to discard the tests if you feel they are not necessary.
> 
> Let us know if you have any concerns.
> 
> Regards,
> Tibor

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:security

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Apologies for the force-pushes and multiple tests, hopefully this is the last one.

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:security

**Comment by csierra** [comment]
Pull request submitted to https://github.com/stian-sigvartsen/liferay-portal/pull/177. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
