### PR TITLE
LPS-96516 Rename util classes and methods

### PR DESCRIPTION
**Pull request by martamedio**
Hey @csierra 

Please, see: https://github.com/brianchandotcom/liferay-portal/pull/80617#issuecomment-553654311

Take into account:
- We shouldn't revert https://github.com/brianchandotcom/liferay-portal/commit/37f4f35e07e3ff888b5512509aef0e4b82f16174, it is necessary to apply the fix that has been done in master
- I added two commits on top of https://github.com/csierra/liferay-portal/pull/568 applying the two changes Brian has requested (avoid chaining + rename)

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reopen

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81312. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
