### PR TITLE
LPS-115694 Check the proper groupId when working with teams since they are not sync between Staging and Live

### PR DESCRIPTION
**Pull request by achaparro**
Hi @csierra,

We were working on this pull long time ago and @ChrisKian made an adjustment since we found a bug and this is the final version of it.

You can have more context in:
https://issues.liferay.com/browse/PTR-1766
https://issues.liferay.com/browse/LPS-115694

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:reevaluate:1197401_7808

**Comment by csierra** [comment]
hey folks, sorry for the late response... 
can't we add the code we are adding to AdvancedPermissionChecker to StagingPermissionChecker? at the end of the day it is a wrapper so it would have the opportunity to change the parameters and add the cache

**Comment by ChrisKian** [comment]
Hi @csierra,
The changes added to AdvancedPermissionChecker are pretty minimal, so I'm not sure what we would move over to StagingPermissionChecker.  The only functional change is [this line](https://github.com/csierra/liferay-portal/pull/800/files#diff-7849c32606eaa62135b8cb3fae5c7f42ec6808c65064f6bf5403c9dc66833197R430-R432) where we try to use the groupId we set earlier (if available).

Please let me know if you meant for something else to be changed, or if I am missing your point.  Thank you!

**Comment by csierra** [comment]
hi @ChrisKian, 
I would appreciate if we could explore that possibility since AdvancedPermissionChecker is a very tangled classed already. Any change to it, albeit minimal, can have huge impact that can be later very difficult to trace. So I believe it would be best if we could keep all the things related to staging in the staging wrapper, if possible. 

Bests,

**Comment by ChrisKian** [comment]
Hi @csierra,
The only way to cleanly resolve this issue without calling the StagingPermission wrapper from the AdvancedPermissionChecker class is to copy several methods from AdvancedPermissionChecker to StagingPermissionChecker.  These methods include _hasGuestPermission(), _hasPermissionImpl(), _hasUserPermissionImpl, hasPermission(), doGetRoleIds(), etc.  We could also make these methods public or move them to the base class.

My point is, I feel these ideas would cause far more changes to AdvancedPermissionChecker than the currently proposed commit, which would have no impact on non-staging sites.  I can definitely pursue this path, but I want to make sure I'm correct in doing so.

Please let me know what you think, or if there are any suggestions on your end.  Thank you!

**Comment by csierra** [comment]
Hi @ChrisKian, 

I see your point. Alas I am not into this issue enough to be able to see or assess if other ways are going to be better or worse. 
Just one thing, is it possible to create tests that describe the behavioral change? As the pull is now I am not confident to entertain any changes because I don't know if I would be breaking it. 

Carlos.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/csierra/liferay-portal/pull/802

Please feel free to close this PR, thanks!

**Comment by lipusz** [comment]
Hello @ChrisKian 

Can you please send the new pull to @liferay-appsec instead and assign the ticket to Product Team App Sec? Just to make sure it doesn't slip under our radar.  :-)

Thanks!

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
