### PR TITLE
[TECHNICAL-SUPPORT] LPS-56833

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @csierra 

I had sent this to Igor first, but he is on vacation: https://github.com/igorspasic/liferay-portal/pull/87#issuecomment-121136904

You're the next in line for APIs & Web services team according to https://docs.google.com/spreadsheets/d/1-IfoPK9ORVkvTapzaS1yWGkFreCrkEyOyet7KAlaTSo/edit#gid=0

**Comment by csierra** [comment]
Hey @hhuijser, 

that is correct, but I don't have much experience with this impl. I will do my best to review this one. 

Bests!

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @yuhai @hhuijser 

would it be possible to create some tests to exemplify this bug and prove the fix, like the ones here: https://github.com/liferay/liferay-portal/tree/master/modules/portal/portal-json-web-service-extender/test/integration or something like this. 

I could assist with this task, or @cgoncas or @mdelapenya

Bests!

**Comment by yuhai** [comment]
Hi @csierra 

I think the fix logic (or the issue reproduction case) is not simplied. It is difficult to write the test. Could you please check the fix explanation and the issue occured case by referring to the below link?

https://issues.liferay.com/browse/LPS-56833?focusedCommentId=636316&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-636316

https://in.liferay.com/web/support/forums/-/message_boards/message/15755239#_19_message_15940243

Regards,
Hai

**Comment by csierra** [comment]
Hey Hai, 

for what I understand the problem is in the LiferaySerializer, isn't it? 

Wouldn't it be possible to isolate the issue and create a test just for the LiferaySerializer without involving other plugins and stuff? I am asking out of ignorance here. 

Otherwise for me reviewing this would be a shoot in the dark because I am not very familiar with this implementation. 

Just let me know if we can help you in any way...

Bests.

**Comment by hhuijser** [comment]
See https://github.com/csierra/liferay-portal/pull/85

**Pull request closed without merging**
