### PR TITLE
OAUTH2-283 Added new properties to add analytics entries as SAP System entries

### PR DESCRIPTION
**Pull request by martamedio**
cc/ @stian-sigvartsen

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/martamedio/liferay-portal/pull/106. [See changes here.](https://github.com/csierra/liferay-portal/compare/2d6d24ae30f9~6...2d6d24ae30f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/809. [See changes here.](https://github.com/csierra/liferay-portal/compare/59fda2ae3814~7...59fda2ae3814) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80305. [See changes here.](https://github.com/csierra/liferay-portal/compare/365707da4282~7...365707da4282) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
