### PR TITLE
LPS-75072 Unlock time shouldn't be shown when the user's account mus be unlocked manually

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

Please find my solution suggestion for LPS-75072 in the pull request.
Could you please review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @csierra,
  did you have a chance to take a look to this PR?
Thanks in advance.

**Comment by csierra** [comment]
@marianoalvarosaiz 
argh... no, I didn't...
I will probably forward it to somebody else 😖

**Comment by csierra** [comment]
@topolik @stian-sigvartsen

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/52409 Thanks

**Comment by topolik** [comment]
ci:close

**Pull request closed without merging**
