### PR TITLE
LPS-107402

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hi @yxingwu,

we can't upgrade CXF like this in the whiteboard. This would probably upgrade some of its dependencies but not the CXF that comes bundled inside. 
We would need to get the whiteboard upgraded first and then upgrade in the portal. 

Thx.

**Pull request closed without merging**
