### PR TITLE
LPS-105158 - UI Scopes Tree

### PR DESCRIPTION
**Pull request by martamedio**
Hey @csierra & @stian-sigvartsen

Here is the second iteration (see the first one [here](https://github.com/csierra/liferay-portal/pull/598)) for the implementation of the new UI for OAuth2 Scopes.
We have developed a hierarchical tree view of the scopes, using JSP 2.0 for generate a custom taglib (_scopes-tree.tld_) and a Java library of graph to create the necessary data structure 🤓 

I do not think that this is a final version, we must iterate to try to simplify the code and make it more readable. Right now some problems I see are:
- The new taglib is too custom for this screen, we could think of doing something generic to show trees (but right now I don't see myself able to estimate how long this would take)
- Due to the rules of SF, I consider that many of the lambdas used become difficult to read because we need to avoid chaining
- Probably some of the methods can be refactored to make them shorter/simpler, but I'm so used to the code that I haven't known where to cut ✂️ 
- Some classes/properties need to be renamed (that _SimpleDisplayContext_ with the tree/map algorithm is no longer "simple" :trollface: )

I would also appreciate it if you could take a look at functional level, please note that:
- This screen should only be displayed if the user is not an OmniAdmin: create a new Virtual Instance and a new user in that instance with an _Administrator_ role
- I have based on [this design of the screen](https://www.figma.com/file/UmZlJwIqCeqKHr3WlOWGim/lps-105158-jax-rs-applications-scopes?node-id=1%3A2), available at Figma.
- Scopes have their own entity: checking all the children of a Scope does not imply selecting its parent Scope ([visual example](https://user-images.githubusercontent.com/19305424/73540749-0703d780-4431-11ea-9f0e-8db1185378a2.png): a parent has more permissions than all his children's permissions). Of course, selecting the parent Scope means selecting all the childrens.
- To detect the deleted Scopes I have simply checked which Scopes are selected that are not present in the list of Scopes generated by the _OAuth2ScopeGrantLocalService_. I'm not sure if I'm missing something else.

I look forward to your feedback and thank you for your help during this development 😍!

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @martamedio, for sure there's stuff missing but this looks good!

**Comment by martamedio** [comment]
Please @csierra and @stian-sigvartsen, check this new PR: https://github.com/csierra/liferay-portal/pull/623

**Pull request closed without merging**
