### PR TITLE
Lps 80517 3

### PR DESCRIPTION
**Pull request by shuyangzhou**
@csierra sorry about the SF change broke your code. Here are the fixes we made to enable the dynamic behavior for those components. Let me know if you see any issues.

@rotty3000 @mhan810 this is the last part of fixing, and actually the only part that is real issue. The others are all noises (like the ResourceImporter case I showed you earlier) rather than real problem. So it is really just @csierra 's code is affected. Once this pull gets in master, we will be fine.

### CODE REVIEW

**Comment by csierra** [comment]
hey @shuyangzhou, thanks for the fix!

no need to apologize, I know we are all trying to make everything work in the best way possible!

**Comment by csierra** [comment]
hi again... why is this all needed? is there a bug in SCR? 
have we tried with the latest SCR version to see whether this is still a problem? because it looks we are doing the kind of stuff that SCR should take care of, aren't we?

**Comment by shuyangzhou** [comment]
@csierra this started as a bug fix for https://issues.liferay.com/browse/APIO-178 .
Then we think this could happen to other usages too, so we have Hugo created the SF rule.
@rotty3000 mentioned the latest SCR release could have it fixed. But we are not going to update it before release for 2 reasons.
1) We have not really tested it to confirm it truly solved the issue we saw. Most likely it does, just we don't know for sure.
2) We have not upgraded SCR for a long time, we don't really know how the new release is different from what we currently have. Doing the upgrade before release is considered risky. Our primary goal now is stability. So we are going with what is known to be safe, which is work around this SCR bug.

From the SF rule output, the only 3 real broken changes are all inside this pull, otherwise are all fine. So we want to keep all usages following the same rule, so that we can guide other developers to go this direction in the future.
Although technically changes in this pull may not be needed anymore after the upgrade(which we will try to do it after release.), switching from STATIC to DYNAMIC can also give us better performance when dealing with dependency changes.

There is one other option here (@rotty3000, @mhan810 and I talked about it yesterday, we don't really want to do it unless it is really necessary), which is SF exclude these 3 usages. So SF won't complain about them. The downside for it is, once we start to allow exceptions, others may follow. We have manually confirmed your code is fine, but we don't want to periodically manually recheck the exclude list to make sure others' code is fine too. So we want to keep everyone inline as long as we can. But of course if one day one special case pops up, that we really can not make it DYNAMIC, we will open the exclude list for it.

Hope this makes sense to you.

**Comment by csierra** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/6220. [See changes here.](https://github.com/csierra/liferay-portal/compare/1513d43~3...1513d43) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/6236. [See changes here.](https://github.com/csierra/liferay-portal/compare/6850040~2...6850040) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
