### PR TITLE
Lps 101720 carlos review reduced

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82964. [See changes here.](https://github.com/csierra/liferay-portal/compare/76a57b0f9659~1...76a57b0f9659) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
