### PR TITLE
LPS-105151 Squashed version

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
As discussed, this is the same as stian-sigvartsen/liferay-portal/pull/250 but 5 commits unrelated to our final approach are squashed into 7c6e25a. Please can you forward to BChan?

/cc @martamedio

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:stop

**Pull request closed without merging**
