### PR TITLE
PTR-108 Avoids printing module versions as well

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/785. [See changes here.](https://github.com/csierra/liferay-portal/compare/3bb3c98~1...3bb3c98) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
