### PR TITLE
LPS-58529 Create a ResourceBundleUtil class to load language keys as UTF8 encoded

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Remerged now.

**Comment by izaera** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30109. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
