### PR TITLE
LPS-55526 Extract stores to OSGi modules

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/453. [See changes here.](https://github.com/csierra/liferay-portal/compare/2f0c766~4...2f0c766) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
