### PR TITLE
LPS-63462

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/36369

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36412. [See changes here.](https://github.com/csierra/liferay-portal/compare/405ee5d~1...405ee5d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/36412

**Pull request closed without merging**
