### PR TITLE
LPS-108590 DB Partitioning: we need to set the companyThreadLocal when we iterate through companies

### PR DESCRIPTION
**Pull request by achaparro**
Hi @csierra,

This is what we discussed a couple of weeks ago. For now, I have defined only the util methods which are useful at this point.

What do you think? Please, send it to @shuyangzhou if are ok with it after your review.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @csierra I have to fix some tests but let me know if this is the proper approach.

**Comment by csierra** [comment]
Please see https://github.com/achaparro/liferay-portal/pull/730

**Pull request closed without merging**
