### PR TITLE
OAUTH2-214 plus tests - fixed TOCTOU test fail

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Carlos. Taking note of your comment https://github.com/topolik/liferay-portal/pull/577#issuecomment-409953466

I agree that introducing the update method is what we were missing!
I am also happy with considering scope alias list sorting part of the API. I had the opposite idea in my earlier commits, i.e. the OAuth2ApplicationScopeAliasesLocalService would allow you to insert unordered ones, but with OAuth2ApplicationLocalService as its caller enforcing sorting.

I fixed a couple of issues:

- The only issue I found was that we are updating the modified time inconsistently sometimes (fixed in 03f60cf) .
- When updateScopesAliases() creates a returns a new ScopeAliases, this is not picked up by the caller, so the OAuth2Application is not updated with the new ScopeAliasesId (fixed in ebba62c)

I've included the tests in this pull as you suggested. The tests pass.

If you (and @topolik ?) are happy then squash and send to Brian?
(Possibly sending the tests starting at b233edf separately)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by csierra** [comment]
> I am also happy with considering scope alias list sorting part of the API.
I guess it cannot be part of the API. We need to internally always sort the list because we need to calculate the hash of the string and so we need it to be consistent for every list passed with the same values. We should not put that burden on the caller since I would say it is an internal implementation detail. 

We might had even had to ask for a `Set` to make sure there are no duplicates in there

**Comment by stian-sigvartsen** [comment]
If sorting was external then you could have different lists with same scopeAliases and different hashes. I think it could work but I don't think it is necessary, and error prone. I much prefer your way. Also like the idea of using a `Set` instead of List on `*LocalService`, but have some reservation because there is a `OAuth2ApplicationScopeAliases.setScopeAliases(String)` method exposed by SB since we're storing these in a varchar field. This implies an ordering.

**Comment by csierra** [comment]
Pull request submitted to https://github.com/stian-sigvartsen/liferay-portal/pull/119. [See changes here.](https://github.com/csierra/liferay-portal/compare/c62b36a~2...c62b36a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
