### PR TITLE
LPS-104838 Consider user time zone when creating the unlock date.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Please, see: https://github.com/brianchandotcom/liferay-portal/pull/81307

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/martamedio/liferay-portal/pull/116. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
