### PR TITLE
LPS-64349 Cannot create RESTExtender config

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-64349](https://issues.liferay.com/browse/LPS-64349).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @drewbrokke 

If I remember correctly this is still caused by Configuration Admin that incorrectly sends an array of Strings with one empty string when nothing is set in the interface (I can't find the LPS now)

Anyhow it is ok that we sanitize our inputs... thanks for the pull!

**Comment by csierra** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/182. [See changes here.](https://github.com/csierra/liferay-portal/compare/45cba08~1...45cba08) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
