### PR TITLE
LPS-91514 Add cors test module

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/721. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69259. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69337. [See changes here.](https://github.com/csierra/liferay-portal/compare/bc308246~1...bc308246) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69341. [See changes here.](https://github.com/csierra/liferay-portal/compare/526d0f2~1...526d0f2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
