### PR TITLE
LPS-75781 Remove export packages from portal-configuration-extender

### PR DESCRIPTION
**Pull request by tinatian**
Hi Carlos,

Our team is trying to decouple modules by removing export packages, and I am working on "portal-configuration-extender" which you added in LPS-59342.

After searching on our code base, I found on other usages of the classes in export packages except in this module, so I moved them into internal packages, also I did some refactoring to make code clean. Could you please review my change?

I know the reason those classes were in public package instead of internal package might be we would like to add other different implementation, but since we have no other implementation now, I think it's better to make it internal, we can move them out when we needed. 

Any question about my changes, please feel free to let me know.

cc @shuyangzhou

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by csierra** [comment]
hey @tinatian, 
> I know the reason those classes were in public package instead of internal package might be we would like to add other different implementation
I wasn't necessarily thinking about us when exporting that. When I exported this I considered this to be an extension point, available for us to third party developers as well. Do you think the bundle is coupling just because it exports a package?
We are not heavily using this module anyway, so I won't oppose to any changes you want to make. I am just concerned if we shortcut _exports => coupling_ or we think that a module only should export something when we are using the functionality in our codebase. What do you think?

My only concern, and that's the reason why I left this extension point, is that we might need a more powerful format (like JSON or YAML) to support some configurations.

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by tinatian** [comment]
Hi @csierra,
Thanks for your time of reviewing my code.

Actually removing export packages is just part of decoupling, and decoupling is an important step of our LPKG tasks. Our current rule for exporting packages is like you said "only should export something when we are using the functionality in our codebase". We are applying this rule in our code base right now, not only for this module, since this way will help us decouple the big LPKG problem into small parts, so that we can work on them one by one.


Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @csierra,

For the extension you are talking about, I think we can create a new module naming ***-api to include all the interfaces needed when it is really needed, instead of exporting the interface packages with implementation classes, and this is what OSGi recommended too.

What do you think?

Thanks.
Tina.

**Comment by csierra** [comment]
I just wanted to make sure I understood it correctly. 
>  I think we can create a new module naming ***-api to include all the interfaces needed

sounds great to me 👍 
> when it is really needed

so extension points normally are not used in our codebase, but still are needed for third party devs to use. If we plan to put these in `-api` modules that's great. My only concern is _when it is needed_ because it seems to imply that we are not going to design the extension points until we use them ourselves. 

That's my only concern.

**Comment by tinatian** [comment]
Hi @csierra,
By "when it is really needed", I mean either we have a customer requiring it or we want to use it our own.
 I am not sure how we deal with "extensions" normally, or for ce users. 

According to my experience in Liferay, most time we leave some "extensions" points for people, and people might not know or no one is using it. So I prefer to only give people an "extension" point only when we know people actually need it. 

This way, we have more control with our API,  save us some effort on maintenance, and finally we can provide people high quality API which will affect most people. For the edge case users, if we hear from them, we still have a way to deal with it.

What do you think?

Thanks.
Tina.

**Comment by csierra** [comment]
Hey... 
thanks for the explanation. 
Sure... go ahead. If in the future we know of some extensions that our customers require, even though we don't use it ourselves, we will be sure to communicate it properly.

For what is worth regarding this module, I am ok if you are ok. 

Thanks for taking care.

Carlos.

**Comment by tinatian** [comment]
Great! Thanks @csierra !

**Comment by csierra** [comment]
thanks to you!

**Pull request closed without merging**
