### PR TITLE
LPS-96516 Semver

### PR DESCRIPTION
**Pull request by martamedio**
Hey @csierra

As we have spoken, I send you this PR related to an LDAP refactor.

What has been done is generate a new set of "SafeLdap" classes to ensured that during all the process we're using type safety and also unify the escaping of parameters related to LDAP.

You can see the original PR [here](https://github.com/martamedio/liferay-portal/pull/108)
A question has been raised about whether we should allow mix template with non-template filter (see it [here](https://github.com/martamedio/liferay-portal/pull/108/commits/0feba56286ba4ab72d69e26b9cf035f578b88ec2)) but we have agreed to leave it as it is (no mixing), to avoid complicate the solution bearing in mind that this is just an issue (not a feature) and are already extending the options for the user

cc/ @topolik

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Thanks @martamedio!

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80529. [See changes here.](https://github.com/csierra/liferay-portal/compare/18117fd6df85~11...18117fd6df85) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80536. [See changes here.](https://github.com/csierra/liferay-portal/compare/c5fb0dbc8c03~13...c5fb0dbc8c03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80577. [See changes here.](https://github.com/csierra/liferay-portal/compare/c60f4ccde094~13...c60f4ccde094) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80589. [See changes here.](https://github.com/csierra/liferay-portal/compare/5f662d6d2568~13...5f662d6d2568) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80591. [See changes here.](https://github.com/csierra/liferay-portal/compare/6a4a5f9f9faa~13...6a4a5f9f9faa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80617. [See changes here.](https://github.com/csierra/liferay-portal/compare/7ea33e9c08f3~14...7ea33e9c08f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
