### PR TITLE
LPS-108633 Wrap Permission Checker

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @csierra 

This pull contains 3 tickets:

1- LPS-108718 (Add depot owner permission automatically), already send it to @brianchandotcom: https://github.com/brianchandotcom/liferay-portal/pull/84667

2- LPS-108719 (Add depot member permission automatically), already send it to @brianchandotcom: https://github.com/brianchandotcom/liferay-portal/pull/84668

3- LPS-108633 (Wrap permission checker with our own)

I only need you to review LPS-108633 , but I have send everything so tests can works. 

Thanks!

/cc @adolfopa

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @csierra 

I have rebased it with current @brianchandotcom  master. So you can avoid future conflicts.

Thanks!

**Comment by csierra** [comment]
thx a ton!

**Comment by csierra** [comment]
Followup https://github.com/brianchandotcom/liferay-portal/pull/85306

**Pull request closed without merging**
