### PR TITLE
LPS-105060 New test to check isolation across companies in OAuth2 without any scopes

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Plase, see: https://github.com/brianchandotcom/liferay-portal/pull/82496

**Pull request closed without merging**
