### PR TITLE
LPS-101720 Remove factory component and generate a MFAPortletURL for generate verify URL

### PR DESCRIPTION
**Pull request by martamedio**
Hey @csierra 
I've tried to fix what BChan requested here: https://github.com/brianchandotcom/liferay-portal/pull/81827#issuecomment-566382618

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82163. [See changes here.](https://github.com/csierra/liferay-portal/compare/436d0fefe395~2...436d0fefe395) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
