### PR TITLE
LPS-58355 Suggestion for this

### PR DESCRIPTION
**Pull request by sammso**
Hi @csierra  

/CC @juangon

I saw that you started to implement LPS-58355. Couple weeks ago, I got annoyed of this issue and made little fix for this. I did discuss this with Juan, but I don't know if he has discussed with you. Anyway, take a look this pull, it fixes Juan's use case + mine, but I'm not sure if I did think everything.

Later, I have also started to think if these PortletDataHandlers should be only registered as "OSGi components" and not directly created by with newInstance as OSGi is dynamic and there should not be references between bundles that are not taken care of.

Other thing is that there are other methods at PortletBagFactory that has also potentially similar problem.

Just let me know, if you want to discuss about this.

### CODE REVIEW

**Comment by juangon** [comment]
Hi @sammso. Thanks for trying that but we already have a fix for this but as it's together with other fixes we have to review more points. Thanks anyway!

**Comment by csierra** [comment]
Hi @sammso, 

I agree with you. The funny thing is that all of that is already been taken care of AFAIU. The problem was that there was a _cached_ value of `getPortletDataHandlerClass()` in an existing PortletImpl, and `getPortletDataHandlerClass()` has extra logic. Making `getPortletDataHandlerClass()` be a plain getter again seems to solve the problem since `newPortletInstances` seems to be taking care of the default value, OSGi services and the legacy ones. 

Thanks anyway... if we see that there are outstanding issues we may cherry-pick some commit from your pull.

**Comment by sammso** [comment]
What is AFAIU ?

**Comment by csierra** [comment]
As Far As I Understand :sweat_smile:

**Comment by sammso** [comment]
Other thing, is that I don't know how to create tests for this and as I see there should be one :)

**Pull request closed without merging**
