### PR TITLE
LPS-49566 regenerate

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/208. [See changes here.](https://github.com/csierra/liferay-portal/compare/239b55f~2...239b55f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/209. [See changes here.](https://github.com/csierra/liferay-portal/compare/69286aa~2...69286aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38033. [See changes here.](https://github.com/csierra/liferay-portal/compare/69286aa~2...69286aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
