### PR TITLE
LPS-101744 buildLang

### PR DESCRIPTION
**Pull request by csierra**
/cc @martamedio

hey Brian... as discussed I send you the updated Language properties...

bests. 
Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by nikki-pru** [comment]
This PR is failing due to the following errors:
`[echo] --- a/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-timebased-otp-service/src/main/java/com/liferay/multi/factor/authentication/timebased/otp/model/impl/MFATimeBasedOTPEntryModelImpl.java`
`[echo] +++ b/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-timebased-otp-service/src/main/java/com/liferay/multi/factor/authentication/timebased/otp/model/impl/MFATimeBasedOTPEntryModelImpl.java`
`[echo] @@ -599,16 +599,17 @@ public class MFATimeBasedOTPEntryModelImpl
[echo]  	}`

[Full Log can be found here](https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/403428/consoleText)

**Comment by csierra** [comment]
please see #742

**Comment by csierra** [comment]
hi @nikki-pru, 
thanks... yes I saw the error log... the problem I had is that those changes in service bulder files do not appear locally, my working copy is clean

**Pull request closed without merging**
