### PR TITLE
OAUTH2-160 Sensible defaults - opinions?

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
I have come up with these changes to achieve what we have discussed over time, hopefully:

1. Scope aliases should automatically grow in scope if more JAX-RS modules are deployed. i.e. no prefix handler by default.
2. We want to map HTTP verbs to the global aliases "everything", "everything.read", "everything.write". However this only makes sense for the "Default" configuration instance. Because if you are not happy with it, your application is is using different scope names. Hence it makes sense to move it into a deployed .config file.
3. ScopeLocatorImpl provides hard coded passthrough impls when there is no ScopeMapper / PrefixHandlerFactory. Consequently we don't need these services always, so set to ConfigurationPolicy.REQUIRE.

I am working on fixing integration tests broken by these changes.

/cc @topolik

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
I don't think anything is tracking "default=true" for ScopeMapper and PrefixHandlerFactory?

**Comment by topolik** [comment]
Oh, you are right! We borrow the one from "Default" JAXRS app. Not sure this is want we want though.

**Comment by stian-sigvartsen** [comment]
I think if you are adding a new application and the osgi.jaxrs.name=Default configuration which maps verbs is not sufficient, then you are not using HttpMethodFeature. So makes sense to start with a clean slate

**Comment by stian-sigvartsen** [comment]
@topolik Just pushed fixes to tests

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Pull request closed without merging**
