### PR TITLE
LPS-63855 Don't require tlds that you provide

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1164. [See changes here.](https://github.com/csierra/liferay-portal/compare/8808887~1...8808887) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1168. [See changes here.](https://github.com/csierra/liferay-portal/compare/3006e6e~2...3006e6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
