### PR TITLE
LPS-106679 BuildLang

### PR DESCRIPTION
**Pull request by martamedio**
Another approach (see: https://github.com/csierra/liferay-portal/pull/751)

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by csierra** [comment]
hey @martamedio, 
I am not sure about this approach because it looks like the submit button does not have to be rendered when there is an exception from the checker but this is not going to be normally the case. There might be many reasons why a checker might throw an exception and it should not imply the submit button does not need to be rendered. do you agree?

**Comment by martamedio** [comment]
Yes...agreed...
It won't be normally the case but there will be some errors/exceptions/validations where we don't want to render it, we have to find an approach to track such cases, but I can't really think of anything that wouldn't fundamentally change the way it works now

**Comment by martamedio** [comment]
Please, see: https://github.com/csierra/liferay-portal/pull/751#issuecomment-650141700

**Pull request closed without merging**
