### PR TITLE
OAUTH2-259 Combining UI expectations from team & some fixes

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
re. UI - I've made an effort to combine all the things we each felt strongly about. Hope you like it.
Also see some functional fixes.

/cc @martamedio @topolik 

Screen Shot 2019-05-02 at 5 30 33 PM
Screen Shot 2019-05-02 at 5 32 36 PM

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72611. [See changes here.](https://github.com/csierra/liferay-portal/compare/32cf96c~1...32cf96c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72718. [See changes here.](https://github.com/csierra/liferay-portal/compare/d68bee6~3...d68bee6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72735. [See changes here.](https://github.com/csierra/liferay-portal/compare/b331081~3...b331081) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
