### PR TITLE
LPS-116141 Add test to check CORS headers obtaining an OAuth2 token

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
Please note that this test will not work until [this PR](https://github.com/brianchandotcom/liferay-portal/pull/90617) is merged

**Comment by martamedio** [comment]
We can take care of [this](https://github.com/brianchandotcom/liferay-portal/pull/90617#issuecomment-649667138) before sending this

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
