### PR TITLE
[TS] LPS-88338 - Moved new methods from PortalUtil to HttpUtil

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @csierra ,

**Previous PR + Comment:** https://github.com/brianchandotcom/liferay-portal/pull/94524#issuecomment-698396094
**Ticket:** https://issues.liferay.com/browse/LPS-88338

Brian mentioned adding the methods to **HttpUtil** instead of **PortalUtil** and that makes sense to me. 

Can you help review and forward if you agree as well and everything looks good?
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
