### PR TITLE
LPS-81227 Added trailing slash when is missing Similar behaviour prior to LPS-81018

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Pull request closed without merging**
