### PR TITLE
LPS-100145 cleanup

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@stian-sigvartsen

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@rotty3000 semver in portal-impl and portal-kernel
```
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.portal.util                            MINOR      3.6.0      3.6.0      3.7.0      VERSION INCREASE REQUIRED
     [echo] 	<   class      com.liferay.portal.util.PropsValues
     [echo] 		+   field      PERMISSION_DYNAMIC_FORBIDDEN_ROLE_NAMES
     [echo] 			+   access     final
     [echo] 			+   access     static
     [echo] 			+   return     java.lang.String[]
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel-4.log
     [echo] ##
     [echo] 
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.portal.kernel.util                     MINOR      9.10.0     9.10.0     9.11.0     VERSION INCREASE REQUIRED
     [echo] 	<   interface  com.liferay.portal.kernel.util.PropsKeys
     [echo] 		+   field      PERMISSION_DYNAMIC_FORBIDDEN_ROLE_NAMES
     [echo] 			+   access     final
     [echo] 			+   access     static
     [echo] 			+   constant   permissions.dynamic.forbidden.role.names
     [echo] 			+   return     java.lang.String
```

**Comment by jpince** [comment]
@rotty3000 @csierra ignore the above results, CII is testing a new infrastructure (note URLs to test-4-1.liferay.com instead of test-1-*.liferay.com). Another GH comment should post with accurate results from test-1

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1435. [See changes here.](https://github.com/csierra/liferay-portal/compare/8aa06369f4f8~3...8aa06369f4f8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
