### PR TITLE
LPS-107404 | LPS-107195

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @csierra ,
If you have any doubts about the parsing when I have left office, there are some explanation in LPS-107404

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
Tests result can also be found here:
https://github.com/arthurchan35/liferay-portal/pull/57

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
Hi @csierra 
I have adjusted commit message as discussed in the meeting.
Let's see what Shuyang says.

**Comment by arthurchan35** [comment]
Sent to https://github.com/shuyangzhou/liferay-portal/pull/8846

**Pull request closed without merging**
