### PR TITLE
OAUTH2-286 Provide bundle symbolic name statically

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Carlos. As discussed this morning, we should simply provide the bundle symbolic name via the builder and drop any LiferayOAuth2Scope resolution.

/cc @topolik

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Test failures look unrelated. But I've realized I didn't adjust the new unit test to the new builder method signature. I will push another commit.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81879. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81887. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81915. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81919. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
