### PR TITLE
[TECHNICAL-SUPPORT] LPS-88353

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ajsampang67

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Guys,

Carlos will review this soon. In the meantime, the fix looks good to be provided in a hotfix. :+1: 

Regards,
Tibor

**Comment by csierra** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66116. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
