### PR TITLE
wip

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
ci:stop

**Comment by csierra** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3352. [See changes here.](https://github.com/csierra/liferay-portal/compare/850ed35~1...850ed35) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/stian-sigvartsen/liferay-portal/pull/43. [See changes here.](https://github.com/csierra/liferay-portal/compare/0208af7~3...0208af7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
ci:stop

**Pull request closed without merging**
