### PR TITLE
LPS-88338 Add tests

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @csierra ,

**Previous PR + Comment:** https://github.com/brianchandotcom/liferay-portal/pull/94594#issuecomment-700162760
**Ticket:** https://issues.liferay.com/browse/LPS-88338

Brian mentioned adding tests for the new methods. I wasn't sure who to forward this to, but I figured you would have the most context regarding the new methods.

Can you help review and forward if the test cases look okay?
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by csierra** [comment]
hi @ericyanLr,

tests look good to me... thx!

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
