### PR TITLE
LPS-60765

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey Carlos,

this is the change we have talked about regarding the module upgrade processes belonging stating.

Please let me know if I should change anything!

thanks,
Daniel

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/510. [See changes here.](https://github.com/csierra/liferay-portal/compare/28c9271~1...28c9271) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
