### PR TITLE
Lps 101720 story

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
please see https://github.com/arthurchan35/liferay-portal/pull/63

**Comment by csierra** [comment]
please see https://github.com/arthurchan35/liferay-portal/pull/63

**Pull request closed without merging**
