### PR TITLE
LPS-100145 Enhance AdvancedPermissionChecker such that contributors can manipulate user roles dynamically

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by csierra** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1434. [See changes here.](https://github.com/csierra/liferay-portal/compare/01c25893cc02~3...01c25893cc02) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
