### PR TITLE
LPS-68402

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!

This is about the mail conversation we had a couple of days ago. Unfortunately, it really seems there's something wrong in ShrinkWrap when specifying both a mirror and a proxy. So I try the approach 3, where I force the Maven resolver to be offline and I provide all the required dependencies. What do you think?

cc @pyoo47

### CODE REVIEW

**Comment by pyoo47** [comment]
@Ithildir If we adopt this approach we will probably need some kind of loop post/documentation so developers know what they need to do when dependencies change.

**Comment by Ithildir** [comment]
Right, but anyway I'm forcing ShrinkWrap to **always** be offline, even during local testing: https://github.com/csierra/liferay-portal/pull/251/commits/02153dc9d4360de00369e1ce3f9e5f3d571e9f89. This way, developers must manually add all the required dependencies if they want to run their tests locally.

ShrinkWrap complains in a nice way, printing out the required artifact. And I think these kind of integration test with an embedded Felix are not that common.

**Comment by csierra** [comment]
hey @Ithildir,

if this is better for you and solves you problems it is fine for me. We will eventually get rid of this version and replace it with the one @cgoncas (and sometimes I) is working on that does not depend on this architecture anymore. 

It is fine for me if you want to forward this to Brian. 

Thanks for the hard work 👏 👏

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/43617.

**Pull request closed without merging**
