### PR TITLE
LPS-102185 fix loop

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
c:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Functional test improvement sent to https://github.com/csierra/liferay-portal/pull/560

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
sent here https://github.com/brianchandotcom/liferay-portal/pull/79507

**Pull request closed without merging**
