### PR TITLE
Lps 111617 CORS Filter

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @csierra 
This pull contains everything from  https://github.com/csierra/liferay-portal/pull/729#issuecomment-646530982.
Also I cleaned up commits by files, with some extra source formatting and stuff, as well as resolved merge conflicts.
I think we can use this pull as base for future changes.

I have run unit tests with this pull, but i have not run any integration tests yet, hope it still passes everything.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:stop

**Comment by csierra** [comment]
Please see https://github.com/csierra/liferay-portal/pull/749

**Pull request closed without merging**
