### PR TITLE
LPS-111672 SF As used

### PR DESCRIPTION
**Pull request by csierra**
/cc @4lejandrito @stian-sigvartsen @topolik

### CODE REVIEW

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/4lejandrito/liferay-portal/pull/457.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
